### ISSUE TITLE
Using JS SDKs

### ISSUE THREAD

**Issue by ersin-ertan** [mvysny/vaadin-kotlin-pwa#3]
Hi, I'm interested in this project coming from Android development. Thanks for putting it together. How will using Kotlin work when certain SDKs are only available on JS? Let's say I wanted to use some of the Firebase SDKs.

Also it wasn't clear to my why "Since we're going to implement the logic server-side to avoid JavaScript, offline mode obviously won't work." this won't work. Offline won't work because we are using JS or it won't work because we don't have a connection. Can we start with a connection then go offline, wouldn't that be considered offline?

**Comment by mvysny** [comment]
Hi, thanks for the message!

A bit of background first. The project is based on Vaadin which originally pushed app logic server-side (that is, the javascript was reduced to "dumb" components, sending every value change event and click event to the server-side). With new Vaadin you can decide how much logic/code you wish to have server-side, and how much of logic you'll have client-side. Let's take a simple form for example. With a form, you can now decide whether you'll have all validation logic client-side and only deliver the data to the server when you press the submit button, or you'll want to have the validation logic server-side, causing all components to push all user-entered values immediately server-side.

The server-side is done in Java or Kotlin, the client-side is done in JavaScript only. I know of Kotlin2JS compiler, but I don't know how well the compilation to web components is supported, that's why I tend to use JS client-side.

The Firebase doesn't exist or work (AFAIK) on pure Java - it only works in the JS. When your data is on the client-side, then there is little sense for having logic server-side. And if the majority of your logic is client-side, then Vaadin (+this project) may not be the best match for you - perhaps you should use React instead (which doesn't use webcomponents and hence the Kotlin2JS compiler might be a good match).

> Offline won't work because we are using JS or it won't work because we don't have a connection. Can we start with a connection then go offline, wouldn't that be considered offline?

The prior one. Vaadin makes most sense when your background is a Java server-side programmer. As a Java server-side programmer, you tend to move the logic server-side and then the client-side need to communicate frequently with the server-side. That inherently doesn't work with offline mode.

I hope this clears things a bit, please feel free to ask any further questions ;)
